export const FETCH_JOBS_SUCCESS = 'FETCH_JOBS_SUCCESS';
export const OPEN_REGISTRATION_MODAL = 'OPEN_REGISTRATION_MODAL';
export const CLOSE_REGISTRATION_MODAL = 'CLOSE_REGISTRATION_MODAL';
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS';
export const CONFIRM_OTP_SUCCESS = 'CONFIRM_OTP_SUCCESS';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';